routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [UserController::class, 'profileShow'])->middleware(['auth'])->name('dashboard');

Route::get('/reports/user', [UserController::class, 'getReportUser'])->middleware(['auth','admin']);;

Route::resource('users', UserController::class)->middleware(['auth','admin']);

Route::patch('/profile/{user}', [UserController::class, 'updateUser'])->name('profile.updateUser')->middleware(['auth']);

Route::resource('posts', PostController::class)->middleware(['auth']);



require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'created_by',
        'date',
        'userId',
        
    ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Role;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rules;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::oldest()->paginate(20);
        return view('posts.index', ['posts' => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $posts = Post::all();

        return view('posts.create', compact('posts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:50'],
            'description' => ['required', 'string', 'max:255'],
            'created_by' => ['', 'string', 'max:50'],
            'date' => ['required', 'string', 'max:50'],


        ]);

        $post = Post::create([
            'name' => $request->name,
            'description' => $request->description,
            'created_by' => $request->created_by,
            'date' =>  $request->date,
            'userId' => Auth::user()->id,

        ]);

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', [
            'post' => $post
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', [
            'post' => $post
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:50'],
            'description' => ['required', 'string', 'max:255'],
            'date' => ['required','string', 'max:50'],
        ]);


        $post = Post::whereId($id)->update([
            'name' => $request->name,
            'description' => $request->description,
            'date' =>  $request->date,
            'userId' => Auth::user()->id,

        ]);

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        $post->delete();

        return redirect()->route('posts.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/posts/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add New Post') }}
        </h2>
    </x-slot>

    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">


                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('posts.store') }}">
                        @csrf

                        <!-- titule -->
                        <div>
                            <x-label for="name" :value="__('Name')" />

                            <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')"
                                required autofocus />
                        </div>

                        <!-- description -->
                        <div>
                            <x-label for="description" :value="__('Description')" />

                            <x-input id="description" class="block mt-1 px-3 py-1.5 text-base w-full " type="text"
                                name="description" :value="old('description')" required autofocus />
                        </div>


                        <!-- writer -->
                        <div>
                            <x-label for="created_by" :value="__('Created by')" />

                            <x-input id="created_by" class="block mt-1 w-full" type="text" name="created_by"
                                :value="Auth::user()->first_name .' '. Auth::user()->last_name" />
                        </div>


                        <!-- date -->
                        <div>
                            <x-label for="date" :value="__('Date')" />

                            <x-input id="date" class="block mt-1 w-full" type="date" name="date" :value="old('date')"
                                required autofocus />
                        </div>

                        <div class="flex items-center justify-end mt-4">
                            <x-button class="ml-4">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/posts/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Post Information') }}
        </h2>
    </x-slot>

    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                <div class="bg-light p-4 rounded">
                    <h1>Update post</h1>
                    <div class="lead">

                    </div>

                    <div class="container mt-4">
                        <x-auth-validation-errors class="mb-4" :errors="$errors" /> 
                        
                        <form method="POST" action="{{ route('posts.update', $post->id) }}">
                            @method('patch')
                            @csrf

                            <!-- titule -->
                            <div>
                                <x-label for="name" :value="__('Name')" />

                                <x-input id="name" class="block mt-1 w-full" type="text" name="name"
                                    :value="$post->name" required autofocus />
                            </div>

                            <!-- description -->
                            <div>
                                <x-label for="description" :value="__('Description')" />

                                <x-input id="description" class="block mt-1 px-3 py-1.5 text-base w-full " type="text"
                                    name="description" :value="$post->description" required autofocus />
                            </div>

                            <!-- created_by -->
                            <div>
                                <x-label for="created_by" :value="__('Created by')" />

                                <label for="">{{$post->created_by}}</label>

                                
                            </div>

                            <!-- date -->
                            <div>
                                <x-label for="date" :value="__('Date')" />
                                <x-label for="date" :value="$post->date" />
                                <x-label for="date" :value="__('New Date')" />

                                <x-input id="date" class="block mt-1 w-full" type="date" name="date"
                                    :value="$post->date"  autofocus />
                            </div>

                            <div class="flex items-center justify-end mt-4">
                                <x-button class="ml-4">
                                    {{ __('Update') }}
                                </x-button>
                                <a href="{{ route('posts.index') }}" class="btn btn-default">Back</a>
                            </div>
                        </form>

                    </div>

                </div>


            </div>
        </div>
    </div>
</x-app-layout>

resources/views/posts/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Post List') }}
        </h2>
    </x-slot>

    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">


                    <div class="bg-light p-4 rounded">
                        <h1>Posts</h1>
                        <div class="lead">

                            <a href="{{ route('posts.create') }}" class="btn btn-primary btn-sm float-right">Add new
                                post</a>
                        </div>


                        <input class="form-control" id="myInput" type="text" placeholder="Search..">
                        <br>

                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th scope="col" width="1%">#</th>
                                    <th scope="col" width="15%">Name</th>
                                    <th scope="col">Description</th>
                                    <th scope="col" width="10%">Created by</th>
                                    <th scope="col" width="10%">Date</th>
                                    <th scope="col" width="1%" colspan="3">Option</th>
                                </tr>
                            </thead>
                            <tbody id="userTable">
                                @foreach($posts as $post)
                                <tr>
                                    <th scope="row">{{ $post->id }}</th>
                                    <td>{{ $post->name}}</td>
                                    <td>{{ $post->description }}</td>
                                    <td>{{ $post->created_by }}</td>
                                    <td>{{ $post->date }}</td>

                                    @if($post->userId == Auth::user()->id || Auth::user()->role == 1 )

                                    <td><a href="{{ route('posts.show', $post->id) }}"
                                            class="btn btn-warning btn-sm">Show</a></td>
                                    <td><a href="{{ route('posts.edit', $post->id) }}"
                                            class="btn btn-info btn-sm">Edit</a></td>
                                    <td>
                                        {!! Form::open(['method' => 'DELETE','route' => ['posts.destroy',
                                        $post->id],'style'=>'display:inline']) !!}
                                        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm']) !!}
                                        {!! Form::close() !!}
                                    </td>
                                    @else
                                    <td></td>
                                    <td></td>
                                    <td></td>

                                    @endif

                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {!! $posts->links() !!}

                    </div>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>
{{-- search in the table --}}
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#userTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

resources/views/posts/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Post Details') }}
        </h2>
    </x-slot>

    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                <div class="bg-light p-4 rounded">
                    <h1>Post by {{ $post->created_by }}</h1>
                    <div class="lead">

                    </div>

                    <div class="container mt-4">
                        <div>
                            Created by: {{ $post->created_by }}
                        </div>
                        <div>
                            Date: {{ $post->date }}
                        </div>
                        <div>
                            Name: {{ $post->name }}
                        </div>
                        <div>
                            Description: {{ $post->description }}
                        </div>

                    </div>

                </div>
                <div class="mt-4">
                    <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-info">Edit</a>
                    <a href="{{ route('posts.index') }}" class="btn btn-default">Back</a>
                </div>


            </div>
        </div>
    </div>
</x-app-layout>